### ISSUE TITLE
Code cleanup running todo list

### ISSUE THREAD

**Issue by alexdanilowicz** [Teddarific/dreamer#8]
- [ ] ensure eslint is working and cleaned up
- [ ] add sentry
- [ ] populate script for prod to local
- [ ] set up running mongo db locally
- [ ] better typescript support with the models
- [ ] idk
